name: Python Workflow
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      aws-default-region:
        required: false
        type: string
        default: "eu-central-1"
      working-directory:
        required: false
        type: string
      test-directory:
        required: false
        type: string
      dependency-file:
        required: false
        type: string
        default: "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    env:
      AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Check out CI repo
        uses: actions/checkout@v3
        with:
          repository: EreminAnton/re-usable-ci
          path: ./re-usable-ci
      - name: Copy pyproject.toml
        run: cp ./re-usable-ci/pyproject.toml ./pyproject.toml
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.dependency-file }}
          pip install pylint pep8 pytest
      - name: Analysing the code with pylint
        continue-on-error: true # allow failures, remove it in the future      
        run: pylint $(git ls-files '*.py')
      - name: Analysing the code with pep8
        continue-on-error: true # allow failures, remove it in the future      
        run: pep8 $(git ls-files '*.py')
      - name: Test with pytest
        continue-on-error: false
        run: pytest ${{ inputs.test-directory }} -v
