name: Terraform Workflow

on:
  workflow_call:
    inputs:
      terraform-version:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Terraform fmt
        run: terraform fmt --recursive -check=true
      - name: Terraform validate
        run: |
            terraform init
            terraform validate -no-color
      - name: Terraform doc
        run: terraform-docs markdown .
      - name: TFSec
        uses: triat/terraform-security-scan@v3.0.3
        with:
          tfsec_actions_comment: false
      - name: TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.46.0
